//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.lang.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Illegal character or unknown number..
        /// </summary>
        internal static string error_Caract {
            get {
                return ResourceManager.GetString("error_Caract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Illegal character. Write &quot;Y&quot; for yes, or &quot;N&quot; for no..
        /// </summary>
        internal static string error_CaractValid {
            get {
                return ResourceManager.GetString("error_CaractValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : The start index must be less than the end index..
        /// </summary>
        internal static string error_index {
            get {
                return ResourceManager.GetString("error_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : the job index cannot be &gt; 5.
        /// </summary>
        internal static string error_JobSuperior5 {
            get {
                return ResourceManager.GetString("error_JobSuperior5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Illegal character or there must only be two indices separated by \&quot;-\&quot;..
        /// </summary>
        internal static string error_listCaract {
            get {
                return ResourceManager.GetString("error_listCaract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : during loading :.
        /// </summary>
        internal static string error_Loading {
            get {
                return ResourceManager.GetString("error_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : BackUpMode code not recognised.
        /// </summary>
        internal static string error_NoneCodeBackup {
            get {
                return ResourceManager.GetString("error_NoneCodeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Invalid destination value.
        /// </summary>
        internal static string error_NoneDestPath {
            get {
                return ResourceManager.GetString("error_NoneDestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Invalid source value.
        /// </summary>
        internal static string error_NoneSourcePath {
            get {
                return ResourceManager.GetString("error_NoneSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Invalid job name..
        /// </summary>
        internal static string error_NoneValidJob {
            get {
                return ResourceManager.GetString("error_NoneValidJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : when saving :.
        /// </summary>
        internal static string error_save {
            get {
                return ResourceManager.GetString("error_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : during full backup :.
        /// </summary>
        internal static string error_saveComplete {
            get {
                return ResourceManager.GetString("error_saveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : during differential backup.
        /// </summary>
        internal static string error_saveDifferential {
            get {
                return ResourceManager.GetString("error_saveDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : The source directory does not exist or could not be found :.
        /// </summary>
        internal static string error_SourcePath_NotFound {
            get {
                return ResourceManager.GetString("error_SourcePath_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Unknown order.
        /// </summary>
        internal static string error_UnknowCmd {
            get {
                return ResourceManager.GetString("error_UnknowCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Value entered not recognised.
        /// </summary>
        internal static string error_UnknowSaisie {
            get {
                return ResourceManager.GetString("error_UnknowSaisie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job Add.
        /// </summary>
        internal static string view_add_AffichJobIsAdd {
            get {
                return ResourceManager.GetString("view_add_AffichJobIsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job No Add.
        /// </summary>
        internal static string view_add_AffichJobIsNoAdd {
            get {
                return ResourceManager.GetString("view_add_AffichJobIsNoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete.
        /// </summary>
        internal static string view_add_complet {
            get {
                return ResourceManager.GetString("view_add_complet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Confirm job creation (Y/N).
        /// </summary>
        internal static string view_add_confirm {
            get {
                return ResourceManager.GetString("view_add_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Target directory address :.
        /// </summary>
        internal static string view_add_destPath {
            get {
                return ResourceManager.GetString("view_add_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        internal static string view_add_diff {
            get {
                return ResourceManager.GetString("view_add_diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (1) - Full mode.
        /// </summary>
        internal static string view_add_modComplet {
            get {
                return ResourceManager.GetString("view_add_modComplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (2) - Differential mode.
        /// </summary>
        internal static string view_add_modDiff {
            get {
                return ResourceManager.GetString("view_add_modDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Job name :.
        /// </summary>
        internal static string view_add_name {
            get {
                return ResourceManager.GetString("view_add_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A job with the same name already exists..
        /// </summary>
        internal static string view_add_sameNameJob {
            get {
                return ResourceManager.GetString("view_add_sameNameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Select backup mode :.
        /// </summary>
        internal static string view_add_SelectMod {
            get {
                return ResourceManager.GetString("view_add_SelectMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Source directory address :.
        /// </summary>
        internal static string view_add_sourcePath {
            get {
                return ResourceManager.GetString("view_add_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The drive specified in the target path.
        /// </summary>
        internal static string view_CantDestPath_1 {
            get {
                return ResourceManager.GetString("view_CantDestPath_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is not available..
        /// </summary>
        internal static string view_CantDestPath_2 {
            get {
                return ResourceManager.GetString("view_CantDestPath_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execution time :.
        /// </summary>
        internal static string view_ExecutionTime {
            get {
                return ResourceManager.GetString("view_ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The maximum number of jobs has been reached..
        /// </summary>
        internal static string view_jobMax {
            get {
                return ResourceManager.GetString("view_jobMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (add) - Add a job.
        /// </summary>
        internal static string view_menu_add {
            get {
                return ResourceManager.GetString("view_menu_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open all.
        /// </summary>
        internal static string view_menu_affichAll {
            get {
                return ResourceManager.GetString("view_menu_affichAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit program.
        /// </summary>
        internal static string view_menu_affichExit {
            get {
                return ResourceManager.GetString("view_menu_affichExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (all) - Sequential execution.
        /// </summary>
        internal static string view_menu_all {
            get {
                return ResourceManager.GetString("view_menu_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start (S) Modify (M) Delete (D).
        /// </summary>
        internal static string view_menu_allCmd {
            get {
                return ResourceManager.GetString("view_menu_allCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The string has been split using &apos;,&apos;..
        /// </summary>
        internal static string view_menu_chainSplit1 {
            get {
                return ResourceManager.GetString("view_menu_chainSplit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The string has been split using &apos;-&apos; characters.
        /// </summary>
        internal static string view_menu_chainSplit2 {
            get {
                return ResourceManager.GetString("view_menu_chainSplit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execution of job number :.
        /// </summary>
        internal static string view_menu_exe {
            get {
                return ResourceManager.GetString("view_menu_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (exit) - Exit the software.
        /// </summary>
        internal static string view_menu_exit {
            get {
                return ResourceManager.GetString("view_menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (lang) - Change language.
        /// </summary>
        internal static string view_menu_lang {
            get {
                return ResourceManager.GetString("view_menu_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job.
        /// </summary>
        internal static string view_menu_nameJob {
            get {
                return ResourceManager.GetString("view_menu_nameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open a backup job.
        /// </summary>
        internal static string view_menu_openJob {
            get {
                return ResourceManager.GetString("view_menu_openJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (param) - Parameters.
        /// </summary>
        internal static string view_menu_param {
            get {
                return ResourceManager.GetString("view_menu_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification of job number :.
        /// </summary>
        internal static string view_modif {
            get {
                return ResourceManager.GetString("view_modif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select what you wanted to change and enter the new data:.
        /// </summary>
        internal static string view_modif_affich {
            get {
                return ResourceManager.GetString("view_modif_affich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (apply) - Apply modification.
        /// </summary>
        internal static string view_modif_apply {
            get {
                return ResourceManager.GetString("view_modif_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (3) Target directory address :.
        /// </summary>
        internal static string view_modif_destPath {
            get {
                return ResourceManager.GetString("view_modif_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (exit) - Return to menu.
        /// </summary>
        internal static string view_modif_exit {
            get {
                return ResourceManager.GetString("view_modif_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (4) Backup mode (1-Complete / 2-Differential) :.
        /// </summary>
        internal static string view_modif_modAffich {
            get {
                return ResourceManager.GetString("view_modif_modAffich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (1) Job name :.
        /// </summary>
        internal static string view_modif_name {
            get {
                return ResourceManager.GetString("view_modif_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (2) Source directory address :.
        /// </summary>
        internal static string view_modif_sourcePath {
            get {
                return ResourceManager.GetString("view_modif_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid backup type.
        /// </summary>
        internal static string view_NoneTypeSave {
            get {
                return ResourceManager.GetString("view_NoneTypeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open backup job 1.
        /// </summary>
        internal static string view_open1 {
            get {
                return ResourceManager.GetString("view_open1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open backup job 2.
        /// </summary>
        internal static string view_open2 {
            get {
                return ResourceManager.GetString("view_open2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open backup job 3.
        /// </summary>
        internal static string view_open3 {
            get {
                return ResourceManager.GetString("view_open3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open backup job 4.
        /// </summary>
        internal static string view_open4 {
            get {
                return ResourceManager.GetString("view_open4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open backup job 5.
        /// </summary>
        internal static string view_open5 {
            get {
                return ResourceManager.GetString("view_open5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The format for saving Logs and States files has been changed to .JSON.
        /// </summary>
        internal static string view_param_AffichJSON {
            get {
                return ResourceManager.GetString("view_param_AffichJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The format for saving Logs and States files has been changed to .XML.
        /// </summary>
        internal static string view_param_AffichXML {
            get {
                return ResourceManager.GetString("view_param_AffichXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (1) - .JSON.
        /// </summary>
        internal static string view_param_json {
            get {
                return ResourceManager.GetString("view_param_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Logs and States files in :.
        /// </summary>
        internal static string view_param_titre {
            get {
                return ResourceManager.GetString("view_param_titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (2) - .XML.
        /// </summary>
        internal static string view_param_xml {
            get {
                return ResourceManager.GetString("view_param_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full backup successful..
        /// </summary>
        internal static string view_saveComplete {
            get {
                return ResourceManager.GetString("view_saveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential backup successful..
        /// </summary>
        internal static string view_SaveDifferential {
            get {
                return ResourceManager.GetString("view_SaveDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The source directory is empty:.
        /// </summary>
        internal static string view_SourcePathEmpty {
            get {
                return ResourceManager.GetString("view_SourcePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job No Delete.
        /// </summary>
        internal static string view_supp_AffichJobIsNoSupp {
            get {
                return ResourceManager.GetString("view_supp_AffichJobIsNoSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job Delete.
        /// </summary>
        internal static string view_supp_AffichJobIsSupp {
            get {
                return ResourceManager.GetString("view_supp_AffichJobIsSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Do you want to delete this job (Y/N).
        /// </summary>
        internal static string view_supp_confirm {
            get {
                return ResourceManager.GetString("view_supp_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete job number :.
        /// </summary>
        internal static string view_suppr {
            get {
                return ResourceManager.GetString("view_suppr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The source directory does not exist or could not be found :.
        /// </summary>
        internal static string view_UnknowSourcePath {
            get {
                return ResourceManager.GetString("view_UnknowSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; .
        /// </summary>
        internal static string view_waitingAswer {
            get {
                return ResourceManager.GetString("view_waitingAswer", resourceCulture);
            }
        }
    }
}
