//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fichierResFr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fichierResFr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.lang.fichierResFr", typeof(fichierResFr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : Caractère illégal ou numéro inconnu..
        /// </summary>
        internal static string error_Caract {
            get {
                return ResourceManager.GetString("error_Caract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : Caractère illégal. Ecrire \&quot;Y\&quot; pour oui, ou \&quot;N\&quot; for no..
        /// </summary>
        internal static string error_CaractValid {
            get {
                return ResourceManager.GetString("error_CaractValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : L’index de début doit être inférieur à l’index de fin..
        /// </summary>
        internal static string error_index {
            get {
                return ResourceManager.GetString("error_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : l&apos;indice du job ne peux être &gt; 5.
        /// </summary>
        internal static string error_JobSuperior5 {
            get {
                return ResourceManager.GetString("error_JobSuperior5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : Caractère illégal ou il ne doit y avoir que deux indices séparés par \&quot;-\&quot;..
        /// </summary>
        internal static string error_listCaract {
            get {
                return ResourceManager.GetString("error_listCaract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : lors du chargement.
        /// </summary>
        internal static string error_Loading {
            get {
                return ResourceManager.GetString("error_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : code BackUpMode non reconnu.
        /// </summary>
        internal static string error_NoneCodeBackup {
            get {
                return ResourceManager.GetString("error_NoneCodeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : La valeur de la destionation n&apos;est pas valide.
        /// </summary>
        internal static string error_NoneDestPath {
            get {
                return ResourceManager.GetString("error_NoneDestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : La valeur de la source n&apos;est pas valide.
        /// </summary>
        internal static string error_NoneSourcePath {
            get {
                return ResourceManager.GetString("error_NoneSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : Le nom du travail n&apos;est pas valide..
        /// </summary>
        internal static string error_NoneValidJob {
            get {
                return ResourceManager.GetString("error_NoneValidJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : lors de la sauvegarde.
        /// </summary>
        internal static string error_save {
            get {
                return ResourceManager.GetString("error_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : lors de la sauvegarde complète.
        /// </summary>
        internal static string error_saveComplete {
            get {
                return ResourceManager.GetString("error_saveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : lors de la sauvegarde différentiel.
        /// </summary>
        internal static string error_saveDifferential {
            get {
                return ResourceManager.GetString("error_saveDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : Le répertoire source n&apos;existe pas ou n&apos;a pas pu être trouvé :.
        /// </summary>
        internal static string error_SourcePath_NotFound {
            get {
                return ResourceManager.GetString("error_SourcePath_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : Commande inconnu.
        /// </summary>
        internal static string error_UnknowCmd {
            get {
                return ResourceManager.GetString("error_UnknowCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : Valeur saisie non reconnu.
        /// </summary>
        internal static string error_UnknowSaisie {
            get {
                return ResourceManager.GetString("error_UnknowSaisie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de langue :.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de log :.
        /// </summary>
        internal static string logType {
            get {
                return ResourceManager.GetString("logType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de State :.
        /// </summary>
        internal static string stateType {
            get {
                return ResourceManager.GetString("stateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail Ajouter.
        /// </summary>
        internal static string view_add_AffichJobIsAdd {
            get {
                return ResourceManager.GetString("view_add_AffichJobIsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail Non Ajouter.
        /// </summary>
        internal static string view_add_AffichJobIsNoAdd {
            get {
                return ResourceManager.GetString("view_add_AffichJobIsNoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complet.
        /// </summary>
        internal static string view_add_complet {
            get {
                return ResourceManager.GetString("view_add_complet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Confirmer la création du travail ? (Y/N).
        /// </summary>
        internal static string view_add_confirm {
            get {
                return ResourceManager.GetString("view_add_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Adresse répertoire cible :.
        /// </summary>
        internal static string view_add_destPath {
            get {
                return ResourceManager.GetString("view_add_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différentiel.
        /// </summary>
        internal static string view_add_diff {
            get {
                return ResourceManager.GetString("view_add_diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (1) - Mode complet.
        /// </summary>
        internal static string view_add_modComplet {
            get {
                return ResourceManager.GetString("view_add_modComplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (2) – Mode différentiel.
        /// </summary>
        internal static string view_add_modDiff {
            get {
                return ResourceManager.GetString("view_add_modDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Nom du travail :.
        /// </summary>
        internal static string view_add_name {
            get {
                return ResourceManager.GetString("view_add_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un job avec le même nom existe déjà..
        /// </summary>
        internal static string view_add_sameNameJob {
            get {
                return ResourceManager.GetString("view_add_sameNameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Sélectionner le mode de sauvegarde :.
        /// </summary>
        internal static string view_add_SelectMod {
            get {
                return ResourceManager.GetString("view_add_SelectMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Adresse répertoire source :.
        /// </summary>
        internal static string view_add_sourcePath {
            get {
                return ResourceManager.GetString("view_add_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le lecteur spécifié dans le chemin cible.
        /// </summary>
        internal static string view_CantDestPath_1 {
            get {
                return ResourceManager.GetString("view_CantDestPath_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à n&apos;est pas disponible..
        /// </summary>
        internal static string view_CantDestPath_2 {
            get {
                return ResourceManager.GetString("view_CantDestPath_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps d&apos;execution :.
        /// </summary>
        internal static string view_ExecutionTime {
            get {
                return ResourceManager.GetString("view_ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre maximal de jobs est atteint..
        /// </summary>
        internal static string view_jobMax {
            get {
                return ResourceManager.GetString("view_jobMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (add) – Ajouter un travail.
        /// </summary>
        internal static string view_menu_add {
            get {
                return ResourceManager.GetString("view_menu_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tout ouvrir.
        /// </summary>
        internal static string view_menu_affichAll {
            get {
                return ResourceManager.GetString("view_menu_affichAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter le programme.
        /// </summary>
        internal static string view_menu_affichExit {
            get {
                return ResourceManager.GetString("view_menu_affichExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (all) - Exécution Séquentielle.
        /// </summary>
        internal static string view_menu_all {
            get {
                return ResourceManager.GetString("view_menu_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer (S) Modifier (M) Supprimer (D).
        /// </summary>
        internal static string view_menu_allCmd {
            get {
                return ResourceManager.GetString("view_menu_allCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La chaîne a été split via des &apos;,&apos;.
        /// </summary>
        internal static string view_menu_chainSplit1 {
            get {
                return ResourceManager.GetString("view_menu_chainSplit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La chaine a été split via des &apos;-&apos;.
        /// </summary>
        internal static string view_menu_chainSplit2 {
            get {
                return ResourceManager.GetString("view_menu_chainSplit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execution du travail numéro :.
        /// </summary>
        internal static string view_menu_exe {
            get {
                return ResourceManager.GetString("view_menu_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (exit) – Quitter le logiciel.
        /// </summary>
        internal static string view_menu_exit {
            get {
                return ResourceManager.GetString("view_menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (lang) - Changer de langue.
        /// </summary>
        internal static string view_menu_lang {
            get {
                return ResourceManager.GetString("view_menu_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail.
        /// </summary>
        internal static string view_menu_nameJob {
            get {
                return ResourceManager.GetString("view_menu_nameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir un travail de sauvegarde.
        /// </summary>
        internal static string view_menu_openJob {
            get {
                return ResourceManager.GetString("view_menu_openJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (param) - Paramètres.
        /// </summary>
        internal static string view_menu_param {
            get {
                return ResourceManager.GetString("view_menu_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification du travail numéro :.
        /// </summary>
        internal static string view_modif {
            get {
                return ResourceManager.GetString("view_modif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez ce que vous vouliez modifier et entrez la nouvelle données :.
        /// </summary>
        internal static string view_modif_affich {
            get {
                return ResourceManager.GetString("view_modif_affich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (apply) - Appliquer la modification.
        /// </summary>
        internal static string view_modif_apply {
            get {
                return ResourceManager.GetString("view_modif_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (3) Adresse du répertoire cible :.
        /// </summary>
        internal static string view_modif_destPath {
            get {
                return ResourceManager.GetString("view_modif_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (exit) - Retour au menu.
        /// </summary>
        internal static string view_modif_exit {
            get {
                return ResourceManager.GetString("view_modif_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (4) Mode de sauvegarde (1-Complet / 2-Différentiel) :.
        /// </summary>
        internal static string view_modif_modAffich {
            get {
                return ResourceManager.GetString("view_modif_modAffich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (1) Nom du travail :.
        /// </summary>
        internal static string view_modif_name {
            get {
                return ResourceManager.GetString("view_modif_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (2) Adresse du répertoire source :.
        /// </summary>
        internal static string view_modif_sourcePath {
            get {
                return ResourceManager.GetString("view_modif_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de sauvegarde invalide.
        /// </summary>
        internal static string view_NoneTypeSave {
            get {
                return ResourceManager.GetString("view_NoneTypeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir un travail de sauvegarde 1.
        /// </summary>
        internal static string view_open1 {
            get {
                return ResourceManager.GetString("view_open1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir un travail de sauvegarde 2.
        /// </summary>
        internal static string view_open2 {
            get {
                return ResourceManager.GetString("view_open2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir un travail de sauvegarde 3.
        /// </summary>
        internal static string view_open3 {
            get {
                return ResourceManager.GetString("view_open3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir un travail de sauvegarde 4.
        /// </summary>
        internal static string view_open4 {
            get {
                return ResourceManager.GetString("view_open4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir un travail de sauvegarde 5.
        /// </summary>
        internal static string view_open5 {
            get {
                return ResourceManager.GetString("view_open5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de sauvegarde des fichiers Logs et States a été modifié en .JSON.
        /// </summary>
        internal static string view_param_AffichJSON {
            get {
                return ResourceManager.GetString("view_param_AffichJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le format de sauvegarde des fichiers Logs et States a été modifié en .XML.
        /// </summary>
        internal static string view_param_AffichXML {
            get {
                return ResourceManager.GetString("view_param_AffichXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (1) - .JSON.
        /// </summary>
        internal static string view_param_json {
            get {
                return ResourceManager.GetString("view_param_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder les fichiers Logs et States sous le format :.
        /// </summary>
        internal static string view_param_titre {
            get {
                return ResourceManager.GetString("view_param_titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (2) - .XML.
        /// </summary>
        internal static string view_param_xml {
            get {
                return ResourceManager.GetString("view_param_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde complète réussie..
        /// </summary>
        internal static string view_saveComplete {
            get {
                return ResourceManager.GetString("view_saveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde différentiel réussie..
        /// </summary>
        internal static string view_SaveDifferential {
            get {
                return ResourceManager.GetString("view_SaveDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le répertoire source est vide:.
        /// </summary>
        internal static string view_SourcePathEmpty {
            get {
                return ResourceManager.GetString("view_SourcePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail Non Supprimer.
        /// </summary>
        internal static string view_supp_AffichJobIsNoSupp {
            get {
                return ResourceManager.GetString("view_supp_AffichJobIsNoSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail Supprimer.
        /// </summary>
        internal static string view_supp_AffichJobIsSupp {
            get {
                return ResourceManager.GetString("view_supp_AffichJobIsSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Voulez-vous supprimer ce travail ? (Y/N).
        /// </summary>
        internal static string view_supp_confirm {
            get {
                return ResourceManager.GetString("view_supp_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer travail numéro :.
        /// </summary>
        internal static string view_suppr {
            get {
                return ResourceManager.GetString("view_suppr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le répertoire source n&apos;existe pas ou n&apos;a pas pu être trouvé :.
        /// </summary>
        internal static string view_UnknowSourcePath {
            get {
                return ResourceManager.GetString("view_UnknowSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; .
        /// </summary>
        internal static string view_waitingAswer {
            get {
                return ResourceManager.GetString("view_waitingAswer", resourceCulture);
            }
        }
    }
}
