//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class langage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langage() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.lang.langage", typeof(langage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new Job.
        /// </summary>
        public static string add_newJob {
            get {
                return ResourceManager.GetString("add_newJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à add.
        /// </summary>
        public static string btn_add {
            get {
                return ResourceManager.GetString("btn_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à delete.
        /// </summary>
        public static string btn_delete {
            get {
                return ResourceManager.GetString("btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string btn_edit {
            get {
                return ResourceManager.GetString("btn_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This extension is already in the list.
        /// </summary>
        public static string error_add_encrypt {
            get {
                return ResourceManager.GetString("error_add_encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid extension format. Please enter the extension starting with a dot..
        /// </summary>
        public static string error_add_format {
            get {
                return ResourceManager.GetString("error_add_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Illegal character or unknown number..
        /// </summary>
        public static string error_Caract {
            get {
                return ResourceManager.GetString("error_Caract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Illegal character. Write &quot;Y&quot; for yes, or &quot;N&quot; for no..
        /// </summary>
        public static string error_CaractValid {
            get {
                return ResourceManager.GetString("error_CaractValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : The start index must be less than the end index..
        /// </summary>
        public static string error_index {
            get {
                return ResourceManager.GetString("error_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : the job index cannot be &gt; 5.
        /// </summary>
        public static string error_JobSuperior5 {
            get {
                return ResourceManager.GetString("error_JobSuperior5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Illegal character or there must only be two indices separated by \&quot;-\&quot;..
        /// </summary>
        public static string error_listCaract {
            get {
                return ResourceManager.GetString("error_listCaract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : during loading :.
        /// </summary>
        public static string error_Loading {
            get {
                return ResourceManager.GetString("error_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : BackUpMode code not recognised.
        /// </summary>
        public static string error_NoneCodeBackup {
            get {
                return ResourceManager.GetString("error_NoneCodeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Invalid destination value.
        /// </summary>
        public static string error_NoneDestPath {
            get {
                return ResourceManager.GetString("error_NoneDestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Invalid source value.
        /// </summary>
        public static string error_NoneSourcePath {
            get {
                return ResourceManager.GetString("error_NoneSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Invalid job name..
        /// </summary>
        public static string error_NoneValidJob {
            get {
                return ResourceManager.GetString("error_NoneValidJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Unable to run Job, notepad application open in background.
        /// </summary>
        public static string error_notepad_open {
            get {
                return ResourceManager.GetString("error_notepad_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : when saving :.
        /// </summary>
        public static string error_save {
            get {
                return ResourceManager.GetString("error_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : during full backup :.
        /// </summary>
        public static string error_saveComplete {
            get {
                return ResourceManager.GetString("error_saveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : during differential backup.
        /// </summary>
        public static string error_saveDifferential {
            get {
                return ResourceManager.GetString("error_saveDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : The source directory does not exist or could not be found :.
        /// </summary>
        public static string error_SourcePath_NotFound {
            get {
                return ResourceManager.GetString("error_SourcePath_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Unable to delete.
        /// </summary>
        public static string error_suppresion {
            get {
                return ResourceManager.GetString("error_suppresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Unknown order.
        /// </summary>
        public static string error_UnknowCmd {
            get {
                return ResourceManager.GetString("error_UnknowCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Value entered not recognised.
        /// </summary>
        public static string error_UnknowSaisie {
            get {
                return ResourceManager.GetString("error_UnknowSaisie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job execution.
        /// </summary>
        public static string exe_job_title {
            get {
                return ResourceManager.GetString("exe_job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension to crypt.
        /// </summary>
        public static string ext_crypt {
            get {
                return ResourceManager.GetString("ext_crypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Files to priorityze.
        /// </summary>
        public static string ext_filespriorityze {
            get {
                return ResourceManager.GetString("ext_filespriorityze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of lang :.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of Log :.
        /// </summary>
        public static string log_Type {
            get {
                return ResourceManager.GetString("log_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à settings have been saved successfully ! .
        /// </summary>
        public static string msgbox_save {
            get {
                return ResourceManager.GetString("msgbox_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of the job :.
        /// </summary>
        public static string nameJob {
            get {
                return ResourceManager.GetString("nameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Release Note.
        /// </summary>
        public static string release {
            get {
                return ResourceManager.GetString("release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run all.
        /// </summary>
        public static string runAll {
            get {
                return ResourceManager.GetString("runAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a folder .
        /// </summary>
        public static string select_folder {
            get {
                return ResourceManager.GetString("select_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size max in ko.
        /// </summary>
        public static string sizemax {
            get {
                return ResourceManager.GetString("sizemax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source directory :.
        /// </summary>
        public static string sourceDir {
            get {
                return ResourceManager.GetString("sourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of State :.
        /// </summary>
        public static string state_Type {
            get {
                return ResourceManager.GetString("state_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target directory :.
        /// </summary>
        public static string targetDir {
            get {
                return ResourceManager.GetString("targetDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a Job.
        /// </summary>
        public static string title_addJob {
            get {
                return ResourceManager.GetString("title_addJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string title_home {
            get {
                return ResourceManager.GetString("title_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of Jobs.
        /// </summary>
        public static string title_listJob {
            get {
                return ResourceManager.GetString("title_listJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs.
        /// </summary>
        public static string title_log {
            get {
                return ResourceManager.GetString("title_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string title_setting {
            get {
                return ResourceManager.GetString("title_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of save :.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete.
        /// </summary>
        public static string typeComplete {
            get {
                return ResourceManager.GetString("typeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        public static string typeDifferential {
            get {
                return ResourceManager.GetString("typeDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Manual.
        /// </summary>
        public static string userManual {
            get {
                return ResourceManager.GetString("userManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job Add.
        /// </summary>
        public static string view_add_AffichJobIsAdd {
            get {
                return ResourceManager.GetString("view_add_AffichJobIsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job No Add.
        /// </summary>
        public static string view_add_AffichJobIsNoAdd {
            get {
                return ResourceManager.GetString("view_add_AffichJobIsNoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complete.
        /// </summary>
        public static string view_add_complet {
            get {
                return ResourceManager.GetString("view_add_complet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Confirm job creation (Y/N).
        /// </summary>
        public static string view_add_confirm {
            get {
                return ResourceManager.GetString("view_add_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Target directory address :.
        /// </summary>
        public static string view_add_destPath {
            get {
                return ResourceManager.GetString("view_add_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        public static string view_add_diff {
            get {
                return ResourceManager.GetString("view_add_diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (1) - Full mode.
        /// </summary>
        public static string view_add_modComplet {
            get {
                return ResourceManager.GetString("view_add_modComplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (2) - Differential mode.
        /// </summary>
        public static string view_add_modDiff {
            get {
                return ResourceManager.GetString("view_add_modDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Job name :.
        /// </summary>
        public static string view_add_name {
            get {
                return ResourceManager.GetString("view_add_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A job with the same name already exists..
        /// </summary>
        public static string view_add_sameNameJob {
            get {
                return ResourceManager.GetString("view_add_sameNameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Select backup mode :.
        /// </summary>
        public static string view_add_SelectMod {
            get {
                return ResourceManager.GetString("view_add_SelectMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Source directory address :.
        /// </summary>
        public static string view_add_sourcePath {
            get {
                return ResourceManager.GetString("view_add_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The drive specified in the target path.
        /// </summary>
        public static string view_CantDestPath_1 {
            get {
                return ResourceManager.GetString("view_CantDestPath_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is not available..
        /// </summary>
        public static string view_CantDestPath_2 {
            get {
                return ResourceManager.GetString("view_CantDestPath_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successful job execution!.
        /// </summary>
        public static string view_exe_successful {
            get {
                return ResourceManager.GetString("view_exe_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execution time :.
        /// </summary>
        public static string view_ExecutionTime {
            get {
                return ResourceManager.GetString("view_ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The maximum number of jobs has been reached..
        /// </summary>
        public static string view_jobMax {
            get {
                return ResourceManager.GetString("view_jobMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (add) - Add a job.
        /// </summary>
        public static string view_menu_add {
            get {
                return ResourceManager.GetString("view_menu_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open all.
        /// </summary>
        public static string view_menu_affichAll {
            get {
                return ResourceManager.GetString("view_menu_affichAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit program.
        /// </summary>
        public static string view_menu_affichExit {
            get {
                return ResourceManager.GetString("view_menu_affichExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (all) - Sequential execution.
        /// </summary>
        public static string view_menu_all {
            get {
                return ResourceManager.GetString("view_menu_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start (S) Modify (M) Delete (D).
        /// </summary>
        public static string view_menu_allCmd {
            get {
                return ResourceManager.GetString("view_menu_allCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The string has been split using &apos;,&apos;..
        /// </summary>
        public static string view_menu_chainSplit1 {
            get {
                return ResourceManager.GetString("view_menu_chainSplit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The string has been split using &apos;-&apos; characters.
        /// </summary>
        public static string view_menu_chainSplit2 {
            get {
                return ResourceManager.GetString("view_menu_chainSplit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execution of job number :.
        /// </summary>
        public static string view_menu_exe {
            get {
                return ResourceManager.GetString("view_menu_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (exit) - Exit the software.
        /// </summary>
        public static string view_menu_exit {
            get {
                return ResourceManager.GetString("view_menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (lang) - Change language.
        /// </summary>
        public static string view_menu_lang {
            get {
                return ResourceManager.GetString("view_menu_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job.
        /// </summary>
        public static string view_menu_nameJob {
            get {
                return ResourceManager.GetString("view_menu_nameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open a backup job.
        /// </summary>
        public static string view_menu_openJob {
            get {
                return ResourceManager.GetString("view_menu_openJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (param) - Parameters.
        /// </summary>
        public static string view_menu_param {
            get {
                return ResourceManager.GetString("view_menu_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification of job number :.
        /// </summary>
        public static string view_modif {
            get {
                return ResourceManager.GetString("view_modif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select what you wanted to change and enter the new data:.
        /// </summary>
        public static string view_modif_affich {
            get {
                return ResourceManager.GetString("view_modif_affich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (apply) - Apply modification.
        /// </summary>
        public static string view_modif_apply {
            get {
                return ResourceManager.GetString("view_modif_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (3) Target directory address :.
        /// </summary>
        public static string view_modif_destPath {
            get {
                return ResourceManager.GetString("view_modif_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (exit) - Return to menu.
        /// </summary>
        public static string view_modif_exit {
            get {
                return ResourceManager.GetString("view_modif_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (4) Backup mode (1-Complete / 2-Differential) :.
        /// </summary>
        public static string view_modif_modAffich {
            get {
                return ResourceManager.GetString("view_modif_modAffich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (1) Job name :.
        /// </summary>
        public static string view_modif_name {
            get {
                return ResourceManager.GetString("view_modif_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (2) Source directory address :.
        /// </summary>
        public static string view_modif_sourcePath {
            get {
                return ResourceManager.GetString("view_modif_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid backup type.
        /// </summary>
        public static string view_NoneTypeSave {
            get {
                return ResourceManager.GetString("view_NoneTypeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open backup job 1.
        /// </summary>
        public static string view_open1 {
            get {
                return ResourceManager.GetString("view_open1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open backup job 2.
        /// </summary>
        public static string view_open2 {
            get {
                return ResourceManager.GetString("view_open2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open backup job 3.
        /// </summary>
        public static string view_open3 {
            get {
                return ResourceManager.GetString("view_open3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open backup job 4.
        /// </summary>
        public static string view_open4 {
            get {
                return ResourceManager.GetString("view_open4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open backup job 5.
        /// </summary>
        public static string view_open5 {
            get {
                return ResourceManager.GetString("view_open5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The format for saving Logs and States files has been changed to .JSON.
        /// </summary>
        public static string view_param_AffichJSON {
            get {
                return ResourceManager.GetString("view_param_AffichJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The format for saving Logs and States files has been changed to .XML.
        /// </summary>
        public static string view_param_AffichXML {
            get {
                return ResourceManager.GetString("view_param_AffichXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (1) - .JSON.
        /// </summary>
        public static string view_param_json {
            get {
                return ResourceManager.GetString("view_param_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Logs and States files in :.
        /// </summary>
        public static string view_param_titre {
            get {
                return ResourceManager.GetString("view_param_titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (2) - .XML.
        /// </summary>
        public static string view_param_xml {
            get {
                return ResourceManager.GetString("view_param_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full backup successful..
        /// </summary>
        public static string view_saveComplete {
            get {
                return ResourceManager.GetString("view_saveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential backup successful..
        /// </summary>
        public static string view_SaveDifferential {
            get {
                return ResourceManager.GetString("view_SaveDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The source directory is empty:.
        /// </summary>
        public static string view_SourcePathEmpty {
            get {
                return ResourceManager.GetString("view_SourcePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job No Delete.
        /// </summary>
        public static string view_supp_AffichJobIsNoSupp {
            get {
                return ResourceManager.GetString("view_supp_AffichJobIsNoSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job Delete.
        /// </summary>
        public static string view_supp_AffichJobIsSupp {
            get {
                return ResourceManager.GetString("view_supp_AffichJobIsSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; Do you want to delete this job (Y/N).
        /// </summary>
        public static string view_supp_confirm {
            get {
                return ResourceManager.GetString("view_supp_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation of deletion.
        /// </summary>
        public static string view_supp_title {
            get {
                return ResourceManager.GetString("view_supp_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete job number :.
        /// </summary>
        public static string view_suppr {
            get {
                return ResourceManager.GetString("view_suppr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The source directory does not exist or could not be found :.
        /// </summary>
        public static string view_UnknowSourcePath {
            get {
                return ResourceManager.GetString("view_UnknowSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &gt; .
        /// </summary>
        public static string view_waitingAswer {
            get {
                return ResourceManager.GetString("view_waitingAswer", resourceCulture);
            }
        }
    }
}
